config/routes.rb
Rails.application.routes.draw do
  get 'welcome/index'
  get 'signup' => 'users#new'

  resources :users

  resources :texts do
    resources :annotations
  end

  root 'welcome#index'


  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/annotation.rb
class Annotation < ApplicationRecord
  belongs_to :text
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/text.rb
class Text < ApplicationRecord
  has_many :annotations, dependent: :destroy
  validates :title, presence: true,
                    length: { minimum: 4 }
end

app/models/user.rb
class User < ApplicationRecord
  #has_secure_password
end

app/controllers/annotations_controller.rb
class AnnotationsController < ApplicationController

  #http_basic_authenticate_with name: "dhh", password: "secret", only: :destroy

  def create
    @text = Text.find(params[:text_id])
    @annotation = @text.annotations.create(annotation_params)
    redirect_to text_path(@text)
  end

  def new
  end

  def destroy
    @text = Text.find(params[:text_id])
    @annotation = @text.annotations.find(params[:id])
    @annotation.destroy
    redirect_to text_path(@text)
  end

  def show
  end

    private
      def annotation_params
        params.require(:annotation).permit(:annotater, :body)
        params.require(:annotation).permit(:annotater, :body)
      end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/texts_controller.rb
class TextsController < ApplicationController

  http_basic_authenticate_with name: "dhh", password: "secret", except: [:index, :show]
  def index
    @texts = Text.all
  end

  def show
    @text = Text.find(params[:id])
  end

  def new
    @text = Text.new
  end

  def edit
    @text = Text.find(params[:id])
  end

  def create
    @text = Text.new(text_params)

    if @text.save
      redirect_to @text
    else
      render 'new'
    end
  end

  def update
    @text = Text.find(params[:id])

    if @text.update(text_params)
      redirect_to @text
    else
      render 'edit'
    end
  end

  def destroy
    @text = Text.find(params[:id])
    @text.destroy

    redirect_to texts_path
  end

  private
    def text_params
      params.require(:text).permit(:title, :artist, :text)
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save!
      session[:user_id] = @user.id
      redirect_to root_path
    else
      redirect_to '/signup'
    end
  end

  private
    def user_params

  params.require(:user).permit(:first_name, :last_name, :email, :password_digest, :native_lang, :target_lang, :interface_lang, :favorite_artist)
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/annotations_helper.rb
module AnnotationsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/texts_helper.rb
module TextsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/annotations/_annotation.html.erb
<% @text.annotations.each do |annotation| %>
<p>
  <strong>Annotater:</strong>
  <%= annotation.annotater %>
</p>

<p>
  <strong>Annotation:</strong>
  <%= annotation.body %>
</p>

  <%= link_to 'Destroy Annotation', [annotation.text, annotation],
               method: :delete,
               data: { confirm: 'Are you sure?' } %>
  <% end %>

app/views/annotations/_form.html.erb
<%= form_for([@text, @text.annotations.build]) do |f| %>
  <p>
    <%= f.label :annotater %><br>
    <%= f.text_field :annotater %>
  </p>
  <p>
    <%= f.label :body %><br>
    <%= f.text_area :body %>
  </p>
  <p>
    <%= f.submit %>
  </p>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>LangreyLearn</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/texts/_form.html.erb
<%= form_for @text do |f| %>

  <% if @text.errors.any? %>
    <div id="error_explanation">
      <h2>
        <%= pluralize(@text.errors.count, "error") %> prohibited
        this song from being saved:
      </h2>
      <ul>
        <% @text.errors.full_messages.each do |txt| %>
          <li><%= txt %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <p>
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </p>

  <p>
    <%= f.label :text %><br>
    <%= f.text_area :text %>
  </p>

  <p>
    <%= f.label :artist %><br>
    <%= f.text_area :artist %>
  </p>

  <p>
    <%= f.submit %>
  </p>

<% end %>

app/views/texts/edit.html.erb
<h1>Edit song</h1>

<%= render 'form' %>

<%= link_to 'Back', texts_path %>

app/views/texts/index.html.erb
<h1>My songs</h1>

<%= link_to 'New song', new_text_path %>

<table>
  <tr>
    <th>Title</th>
    <th>Song</th>
    <th>Artist</th>
    <th colspan="3"></th>
  </tr>

  <% @texts.each do |text| %>
    <tr>
      <td><%= text.title %></td>
      <td><%= text.text %></td>
      <td><%= text.artist %></td>
      <td><%= link_to 'Show', text_path(text) %></td>
      <td><%= link_to 'Edit', edit_text_path(text) %></td>
      <td><%= link_to 'Destroy', text_path(text),
              method: :delete,
              data: { confirm: 'Are you sure?' } %></td>
    </tr>
  <% end %>
</table>

app/views/texts/new.html.erb
  <h1>New Song</h1>
  <%= render 'form' %>

  <%= link_to 'Back', texts_path %>

app/views/texts/show.html.erb
<p>
  <strong>Title:</strong>
  <%= @text.title %>
</p>

<p>
  <strong>Text:</strong>
  <%= @text.text %>
</p>

<h2>Annotations</h2>
<%= render @text.annotations %>

<h2>Add an annotation:</h2>
<%= render 'annotations/form' %>

<%= link_to 'Edit', edit_text_path(@text) %> |
<%= link_to 'Back', texts_path %>

app/views/users/new.html.erb
<%= form_for(@user) do |f| %>
    <%= f.text_field :target_lang, :placeholder => "Target Language" %>
    <%= f.text_field :interface_lang, :placeholder => "Interface Language" %>
    <%= f.text_field :native_lang, :placeholder => "Native Language" %>
    <%= f.text_field :favorite_artist, :placeholder => "Input your favorite artist" %>
    <%= f.submit "Start Learning", class: "btn-submit" %>

    <!--    f.email_field :email, :placeholder => "Email"
        f.password_field :password_digest, :placeholder => "Password"
        f.text_field :first_name, :placeholder => "First Name"
         f.text_field :last_name, :placeholder => "Last Name" -->
<% end %>

app/views/welcome/index.html.erb
<h1>Welcome to LangRey</h1>
<%= link_to 'My Playlist', controller: 'texts' %>